//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Private_University.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Aboutus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Aboutus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Private_University.Resources.Aboutus", typeof(Aboutus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The State Government repealed the Chhattisgarh Niji Kshetra Vishwavidyalaya ( Sthapana Aur Viniyaman ) Adhiniyam 2002 ( Number 2 of 2002) and its Amendment Act of 2004 , and enacted a new Act “The Chhattisgarh Private Universities (Establishment and Operation) Act, 2005 (Number 13 of 2005) , an Act to provide for establishment and for incorporation of self-financed Universities in the State of Chhattisgarh for imparting Higher Education, and to regulate their functions and for matters connected therewith or [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In compliance with the provisions of Section 36 ( Chapter IV) of the Act, the State Government vide Gazette Notification Number 6886/21- A/Drafting/04 (Assent received from the Hon’ble Governor on 17/8/2005) published on 24/8/2005 in the State Government Gazette ( Extra Ordinary ), established a Regulatory Commission, “ The Chhattisgarh Private Universities Regulatory Commission ” for the purpose of providing a regulatory mechanism at the State level, and for working as an interface between the State Govern [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContentTwo {
            get {
                return ResourceManager.GetString("ContentTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Chhattisgarh Private Universities Regulatory Commission.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Us.
        /// </summary>
        public static string Us {
            get {
                return ResourceManager.GetString("Us", resourceCulture);
            }
        }
    }
}
