//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Private_University.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Private_University.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Act Rules &amp; Regulations.
        /// </summary>
        public static string ActRulesAndRegulations {
            get {
                return ResourceManager.GetString("ActRulesAndRegulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector-24, Block 7B, Ground Floor, Nawa Raipur Atal Nagar, Raipur,Chhattisgarh.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chhattisgarh Private Universities Regulatory Commission.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail ID.
        /// </summary>
        public static string EmailId {
            get {
                return ResourceManager.GetString("EmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address - Sector-24, Block 7B, Ground Floor, Nawa Raipur Atal Nagar, Raipur, Chhattisgarh, India.
        /// </summary>
        public static string FooterAddress {
            get {
                return ResourceManager.GetString("FooterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Managed by Department &amp; Designed and Developed by CHiPS.
        /// </summary>
        public static string FooterCopyName {
            get {
                return ResourceManager.GetString("FooterCopyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyrights.
        /// </summary>
        public static string FooterCopyright {
            get {
                return ResourceManager.GetString("FooterCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email- cgpurc18[at]gmail[dot]com.
        /// </summary>
        public static string FooterEmail {
            get {
                return ResourceManager.GetString("FooterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AICTE.
        /// </summary>
        public static string FooterLinkAICTE {
            get {
                return ResourceManager.GetString("FooterLinkAICTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar Council of India.
        /// </summary>
        public static string FooterLinkBarCouncilofIndia {
            get {
                return ResourceManager.GetString("FooterLinkBarCouncilofIndia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department of Higher Education, Chhattisgarh.
        /// </summary>
        public static string FooterLinkHigherEducation {
            get {
                return ResourceManager.GetString("FooterLinkHigherEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Council for Teacher Education.
        /// </summary>
        public static string FooterLinkNcte {
            get {
                return ResourceManager.GetString("FooterLinkNcte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raj Bhawan, Chhattisgarh.
        /// </summary>
        public static string FooterLinkRajBhawan {
            get {
                return ResourceManager.GetString("FooterLinkRajBhawan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University Grants Commission.
        /// </summary>
        public static string FooterLinkUGC {
            get {
                return ResourceManager.GetString("FooterLinkUGC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone - +91-771-2277580.
        /// </summary>
        public static string FooterPhone {
            get {
                return ResourceManager.GetString("FooterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Bearers.
        /// </summary>
        public static string OfficeBearer {
            get {
                return ResourceManager.GetString("OfficeBearer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTI.
        /// </summary>
        public static string Rti {
            get {
                return ResourceManager.GetString("Rti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string TextContactUs {
            get {
                return ResourceManager.GetString("TextContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Links.
        /// </summary>
        public static string TextImportantLinks {
            get {
                return ResourceManager.GetString("TextImportantLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universities.
        /// </summary>
        public static string Universities {
            get {
                return ResourceManager.GetString("Universities", resourceCulture);
            }
        }
    }
}
