//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Private_University.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Private_University.Resources.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAFT University.
        /// </summary>
        public static string AAFTUniversity {
            get {
                return ResourceManager.GetString("AAFTUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMITY University.
        /// </summary>
        public static string AMITYUniversity {
            get {
                return ResourceManager.GetString("AMITYUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anjaneya University.
        /// </summary>
        public static string AnjaneyaUniversity {
            get {
                return ResourceManager.GetString("AnjaneyaUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Details.
        /// </summary>
        public static string AnnualDetails {
            get {
                return ResourceManager.GetString("AnnualDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Report.
        /// </summary>
        public static string AnnualReport {
            get {
                return ResourceManager.GetString("AnnualReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anti-Harassment.
        /// </summary>
        public static string AntiHarassment {
            get {
                return ResourceManager.GetString("AntiHarassment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anti-Ragging.
        /// </summary>
        public static string AntiRagging {
            get {
                return ResourceManager.GetString("AntiRagging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bharti University.
        /// </summary>
        public static string BhartiUniversity {
            get {
                return ResourceManager.GetString("BhartiUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilaspur.
        /// </summary>
        public static string Bilaspur {
            get {
                return ResourceManager.GetString("Bilaspur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPURC.
        /// </summary>
        public static string CGPURC {
            get {
                return ResourceManager.GetString("CGPURC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shri Vishnu Deo Sai.
        /// </summary>
        public static string CMName {
            get {
                return ResourceManager.GetString("CMName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hon&apos;ble Chief Minister of Chhattisgarh.
        /// </summary>
        public static string CMPost {
            get {
                return ResourceManager.GetString("CMPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shir Davara University.
        /// </summary>
        public static string DavaraUniversity {
            get {
                return ResourceManager.GetString("DavaraUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev Sanskriti.
        /// </summary>
        public static string DevSanskriti {
            get {
                return ResourceManager.GetString("DevSanskriti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dr. C.V. Raman University.
        /// </summary>
        public static string DrCVRamanUniversity {
            get {
                return ResourceManager.GetString("DrCVRamanUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durg.
        /// </summary>
        public static string Durg {
            get {
                return ResourceManager.GetString("Durg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gariyaband.
        /// </summary>
        public static string Gariyaband {
            get {
                return ResourceManager.GetString("Gariyaband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shri Ramen Deka.
        /// </summary>
        public static string GovName {
            get {
                return ResourceManager.GetString("GovName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hon`ble Governor of Chhattisgarh.
        /// </summary>
        public static string GovPost {
            get {
                return ResourceManager.GetString("GovPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professor Vijay Kumar Goyal.
        /// </summary>
        public static string HODName {
            get {
                return ResourceManager.GetString("HODName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chairman CGPURC.
        /// </summary>
        public static string HODPost {
            get {
                return ResourceManager.GetString("HODPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICFAI University.
        /// </summary>
        public static string ICFAIUniversity {
            get {
                return ResourceManager.GetString("ICFAIUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBM University.
        /// </summary>
        public static string ISBMUniversity {
            get {
                return ResourceManager.GetString("ISBMUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITM University.
        /// </summary>
        public static string ITMUniversity {
            get {
                return ResourceManager.GetString("ITMUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalinga University.
        /// </summary>
        public static string KalingaUniversity {
            get {
                return ResourceManager.GetString("KalingaUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KK Modi University.
        /// </summary>
        public static string KKModiUniversity {
            get {
                return ResourceManager.GetString("KKModiUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kota Bilaspur.
        /// </summary>
        public static string KotaBilaspur {
            get {
                return ResourceManager.GetString("KotaBilaspur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest News.
        /// </summary>
        public static string LatestNews {
            get {
                return ResourceManager.GetString("LatestNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maharshi University.
        /// </summary>
        public static string MaharshiUniversity {
            get {
                return ResourceManager.GetString("MaharshiUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MATS University.
        /// </summary>
        public static string MATSUniversity {
            get {
                return ResourceManager.GetString("MATSUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nava Raipur.
        /// </summary>
        public static string NavaRaipur {
            get {
                return ResourceManager.GetString("NavaRaipur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objectives.
        /// </summary>
        public static string Objectives {
            get {
                return ResourceManager.GetString("Objectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O.P. Jindal University.
        /// </summary>
        public static string OPJindalUniversity {
            get {
                return ResourceManager.GetString("OPJindalUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Structure.
        /// </summary>
        public static string OrgStruct {
            get {
                return ResourceManager.GetString("OrgStruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Values.
        /// </summary>
        public static string OurValues {
            get {
                return ResourceManager.GetString("OurValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevention of Ragging.
        /// </summary>
        public static string PreventionRagging {
            get {
                return ResourceManager.GetString("PreventionRagging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raigarh.
        /// </summary>
        public static string Raigarh {
            get {
                return ResourceManager.GetString("Raigarh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raipur.
        /// </summary>
        public static string Raipur {
            get {
                return ResourceManager.GetString("Raipur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexual Harassment Prevention.
        /// </summary>
        public static string SexualHarassmentPrevention {
            get {
                return ResourceManager.GetString("SexualHarassmentPrevention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shri Rawatpura Sarkar.
        /// </summary>
        public static string ShriRawatpuraSarkar {
            get {
                return ResourceManager.GetString("ShriRawatpuraSarkar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shri Shankaracharya Professional.
        /// </summary>
        public static string ShriShankaracharyaProfessional {
            get {
                return ResourceManager.GetString("ShriShankaracharyaProfessional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilda Raipur.
        /// </summary>
        public static string TildaRaipur {
            get {
                return ResourceManager.GetString("TildaRaipur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Univsersities.
        /// </summary>
        public static string Universities {
            get {
                return ResourceManager.GetString("Universities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University Bhilai.
        /// </summary>
        public static string UniversityBhilai {
            get {
                return ResourceManager.GetString("UniversityBhilai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University Durg.
        /// </summary>
        public static string UniversityDurg {
            get {
                return ResourceManager.GetString("UniversityDurg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University Raipur.
        /// </summary>
        public static string UniversityRaipur {
            get {
                return ResourceManager.GetString("UniversityRaipur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Record.
        /// </summary>
        public static string WorldRecord {
            get {
                return ResourceManager.GetString("WorldRecord", resourceCulture);
            }
        }
    }
}
