//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Private_University.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Objective {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Objective() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Private_University.Resources.Objective", typeof(Objective).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Chhattisgarh Private Universities Regulatory Commission.
        /// </summary>
        public static string CommName {
            get {
                return ResourceManager.GetString("CommName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objectives.
        /// </summary>
        public static string Objectives {
            get {
                return ResourceManager.GetString("Objectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To ensure that students enrolled in the private university are not exploited and no un-ethical means are adopted to collect undue excessive fee from them..
        /// </summary>
        public static string PointFive {
            get {
                return ResourceManager.GetString("PointFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To ensure that the staff of the private university is appointed in conformity with the Statutes, Ordinance, and norms / guidelines prescribed by UGC and other concerned Statutory Bodies..
        /// </summary>
        public static string PointFour {
            get {
                return ResourceManager.GetString("PointFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To take all such steps as it considers necessary for determination and maintenance of standards of teaching, examination and research in the private universities..
        /// </summary>
        public static string PointOne {
            get {
                return ResourceManager.GetString("PointOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To regulate in consultation with the concerned private university, the study centres established at different places in the state..
        /// </summary>
        public static string PointSeven {
            get {
                return ResourceManager.GetString("PointSeven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To take action pertaining to, and pursuant upon, liquidation of a private university by the state, including arrangement for completion of courses, conduct of examinations, award of degrees etc., by assigning the job to some other state university in such a manner that the interest of the students are not adversely affected. Expenditure made for these arrangements for the students alongwith the process of liquidation of the private university shall be made good from the money deposited in the Endowment Fund [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PointSix {
            get {
                return ResourceManager.GetString("PointSix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To ensure that the teachers of the university have at least the minimum educational qualifications prescribed by the UGC or other Regulatory Bodies..
        /// </summary>
        public static string PointThree {
            get {
                return ResourceManager.GetString("PointThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To ensure that private universities collect only such fees and other charges which cover the cost of education imparted by them and also give a reasonable surplus to enable them to maintain assets and carry out further expansion..
        /// </summary>
        public static string PointTwo {
            get {
                return ResourceManager.GetString("PointTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It shall be the general duty of the Regulatory Commission:.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
