//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Private_University.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OurValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OurValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Private_University.Resources.OurValues", typeof(OurValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Chhattisgarh Private Universities Regulatory Commission.
        /// </summary>
        public static string ComiName {
            get {
                return ResourceManager.GetString("ComiName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Statement:.
        /// </summary>
        public static string MissionStatement {
            get {
                return ResourceManager.GetString("MissionStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a flow of quality human resource capable of meeting the challenges of tomorrow thereby creating wealth for the nation at the forefront of knowledge..
        /// </summary>
        public static string MPointFour {
            get {
                return ResourceManager.GetString("MPointFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To facilitate the Non-Government Organizations ( i.e. non-profit making Trust/Companies/Societies) to establish world class quality university in Chhattisgarh, which would :.
        /// </summary>
        public static string MPointOne {
            get {
                return ResourceManager.GetString("MPointOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare students to face the global challenges with courage and dedication..
        /// </summary>
        public static string MPointThree {
            get {
                return ResourceManager.GetString("MPointThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play a distinctive role in development of professional and higher education..
        /// </summary>
        public static string MpointTwo {
            get {
                return ResourceManager.GetString("MpointTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision &amp; Mission Statement.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        public static string TitleSpan {
            get {
                return ResourceManager.GetString("TitleSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our.
        /// </summary>
        public static string TitleText {
            get {
                return ResourceManager.GetString("TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision Statement:.
        /// </summary>
        public static string VisionStatement {
            get {
                return ResourceManager.GetString("VisionStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To motivate private sector for the development of a centre of excellence leading to world class standards with a honest endeavour in sustaining quality education through modern and best infrastructure thereby contributing to the enrichment of society through high quality higher education and innovation research..
        /// </summary>
        public static string VPointOne {
            get {
                return ResourceManager.GetString("VPointOne", resourceCulture);
            }
        }
    }
}
