//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Private_University.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WorldRecord {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorldRecord() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Private_University.Resources.WorldRecord", typeof(WorldRecord).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Chhattisgarh Private Universities Regulatory Commission.
        /// </summary>
        public static string CommName {
            get {
                return ResourceManager.GetString("CommName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Golden Book of World Records organization presented the certificate of world record to the Governor. The virtual meeting of the Chhattisgarh Private University Regulatory Commission held on 17 December 2020 was recorded in the world record..
        /// </summary>
        public static string PointOne {
            get {
                return ResourceManager.GetString("PointOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This was the first time that a webinar private university had come together and had a long online meeting. The meeting was held under the guidance of Governor Ms. Uike. This meeting has been recorded in the world record. On this occasion, the Chairman of Chhattisgarh Private University Regulatory Commission Shri Shivvaran Shukla, Secretary of the Commission Shri Ramji Dwivedi and Administrative Member of the Commission, Smt. Renu Deshmukh were also present..
        /// </summary>
        public static string PointThree {
            get {
                return ResourceManager.GetString("PointThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raipur, 05 January 2021 / The representative of Golden Book of World Records presented the certificate of world record to Governor Ms. Anusuiya Uikey for the virtual meeting held on 17th December 2020 at Raj Bhavan today. The Governor while thanking for this said that Chhattisgarh Private University Regulatory Commission and its Chairman Shri Shivvaran Shukla deserve congratulations for this. In this, 15 private universities of the state were involved and there was a meaningful dialogue on the quality of hi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PointTwo {
            get {
                return ResourceManager.GetString("PointTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World.
        /// </summary>
        public static string World {
            get {
                return ResourceManager.GetString("World", resourceCulture);
            }
        }
    }
}
